package commands

const (
	SETBITSIZE8 uint8 = iota
	SETROTATEON
	SETROTATEOFF
	SETFLIPON
	SETFLIPOFF
	SETBRIGHTNESS
	DISPLAY
	DELAY
	CLEARDISPLAY
	SETCOLOR
	CLEARCOLOR
	FILLSCREEN
	DRAWPIXEL
	DRAWLINE
	DRAWFASTVLINE
	DRAWFASTHLINE
	DRAWRECT
	FILLRECT
	DRAWCIRCLE
	FILLCIRCLE
	DRAWROUNDRECT
	FILLROUNDRECT
	DRAWTRIANGLE
	FILLTRIANGLE
)

var InstructionForwardMap map[uint8]string = map[uint8]string{
	SETBITSIZE8:   "SETBITSIZE8",
	SETROTATEON:   "SETROTATEON",
	SETROTATEOFF:  "SETROTATEOFF",
	SETFLIPON:     "SETFLIPON",
	SETFLIPOFF:    "SETFLIPOFF",
	SETBRIGHTNESS: "SETBRIGHTNESS",
	DISPLAY:       "DISPLAY",
	DELAY:         "DELAY",
	CLEARDISPLAY:  "CLEARDISPLAY",
	SETCOLOR:      "SETCOLOR",
	CLEARCOLOR:    "CLEARCOLOR",
	FILLSCREEN:    "FILLSCREEN",
	DRAWPIXEL:     "DRAWPIXEL",
	DRAWLINE:      "DRAWLINE",
	DRAWFASTVLINE: "DRAWFASTVLINE",
	DRAWFASTHLINE: "DRAWFASTHLINE",
	DRAWRECT:      "DRAWRECT",
	FILLRECT:      "FILLRECT",
	DRAWCIRCLE:    "DRAWCIRCLE",
	FILLCIRCLE:    "FILLCIRCLE",
	DRAWROUNDRECT: "DRAWROUNDRECT",
	FILLROUNDRECT: "FILLROUNDRECT",
	DRAWTRIANGLE:  "DRAWTRIANGLE",
	FILLTRIANGLE:  "FILLTRIANGLE",
}

var InstructionReverseMap map[string]uint8
