package commands

const (
	SETBITSIZE8 uint8 = iota
	SETROTATEON
	SETROTATEOFF
	SETFLIPON
	SETFLIPOFF
	DISPLAY
	CLEARDISPLAY
	CLEARCOLOR
	SETBRIGHTNESS
	DELAY10MS
	DELAY1S
	DELAY1M
	SETCOLOR
	FILLSCREEN
	DRAWPIXEL
	DRAWLINE
	DRAWFASTVLINE
	DRAWFASTHLINE
	DRAWRECT
	FILLRECT
	DRAWCIRCLE
	FILLCIRCLE
	DRAWROUNDRECT
	FILLROUNDRECT
	DRAWTRIANGLE
	FILLTRIANGLE
	PRINT
)

var InstructionForwardMap map[uint8]string = map[uint8]string{
	SETBITSIZE8:   "SETBITSIZE8",
	SETROTATEON:   "SETROTATEON",
	SETROTATEOFF:  "SETROTATEOFF",
	SETFLIPON:     "SETFLIPON",
	SETFLIPOFF:    "SETFLIPOFF",
	SETBRIGHTNESS: "SETBRIGHTNESS",
	DISPLAY:       "DISPLAY",
	DELAY10MS:     "DELAY10MS",
	DELAY1S:       "DELAY1S",
	DELAY1M:       "DELAY1M",
	CLEARDISPLAY:  "CLEARDISPLAY",
	SETCOLOR:      "SETCOLOR",
	CLEARCOLOR:    "CLEARCOLOR",
	FILLSCREEN:    "FILLSCREEN",
	DRAWPIXEL:     "DRAWPIXEL",
	DRAWLINE:      "DRAWLINE",
	DRAWFASTVLINE: "DRAWFASTVLINE",
	DRAWFASTHLINE: "DRAWFASTHLINE",
	DRAWRECT:      "DRAWRECT",
	FILLRECT:      "FILLRECT",
	DRAWCIRCLE:    "DRAWCIRCLE",
	FILLCIRCLE:    "FILLCIRCLE",
	DRAWROUNDRECT: "DRAWROUNDRECT",
	FILLROUNDRECT: "FILLROUNDRECT",
	DRAWTRIANGLE:  "DRAWTRIANGLE",
	FILLTRIANGLE:  "FILLTRIANGLE",
	PRINT:         "PRINT",
}

var InstructionReverseMap map[string]uint8

func IsTextCommand(cmd byte) bool {
	switch cmd {
	case PRINT:
		return true
	default:
		return false
	}
}
